version: '3'
services:
  db:
    image: mysql:8.0
    command: --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION --max_allowed_packet=1073741824 --group_concat_max_len=1000000
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: projectmanager
      MYSQL_DATABASE: projectmanager
    ports:
      - '${PORTSQL}:3306'
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8082:80'
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: projectmanager

volumes:
  db_data: {}
